version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wallet

  phpmyadmin:
    image: phpmyadmin
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1


