version: "3.7"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - '8080:80'
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
    networks:
      - app-network

  app:
    build: .
    container_name: app
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    ports:
      - '8000:80'
    depends_on:
      - mysql
    networks:
      - app-network
    volumes:
      - ./:/var/www/html

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
